<?php
/**
 * Created by PhpStorm.
 * User: varloteaux
 * Date: 18/10/18
 * Time: 09:42
 */

namespace Model;

/**
 * Class OpinionsTripAdvisorManager
 * @package Model
 */
class OpinionsTripAdvisorManager extends AbstractManager
{
    /**
     *
     */
    const TABLE = 'opinionTripAdvisor';

    /**
     * OpinionsTripAdvisorManager constructor.
     * @param \PDO $pdo
     */
    public function __construct(\PDO $pdo)
    {
        parent::__construct(self::TABLE, $pdo);
    }

    /**
     * @return array
     */
    public function selectAllOpinionsTripAdvisor(): array
    {
        return parent::selectAll(); // TODO: Change the autogenerated stub
    }

}